/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
          950: '#1e1b4b',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        heading: ['Space Grotesk', 'system-ui', 'sans-serif'],
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'float-left': 'floatLeft 50s linear infinite',
        'float-right': 'floatRight 45s linear infinite',
        'glow': 'glow 2s ease-in-out infinite alternate',
        'gradient': 'gradient 8s linear infinite',
        'gradient-slow': 'gradient 20s ease-in-out infinite',
        'slide-up': 'slideUp 0.5s ease-out',
        'slide-down': 'slideDown 0.5s ease-out',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        floatLeft: {
          '0%, 100%': { transform: 'translate(0px, 0px)' },
          '6.25%': { transform: 'translate(15px, -8px)' },
          '12.5%': { transform: 'translate(28px, -18px)' },
          '18.75%': { transform: 'translate(38px, -30px)' },
          '25%': { transform: 'translate(42px, -42px)' },
          '31.25%': { transform: 'translate(40px, -52px)' },
          '37.5%': { transform: 'translate(32px, -58px)' },
          '43.75%': { transform: 'translate(20px, -60px)' },
          '50%': { transform: 'translate(5px, -58px)' },
          '56.25%': { transform: 'translate(-10px, -52px)' },
          '62.5%': { transform: 'translate(-22px, -42px)' },
          '68.75%': { transform: 'translate(-30px, -28px)' },
          '75%': { transform: 'translate(-32px, -12px)' },
          '81.25%': { transform: 'translate(-28px, 5px)' },
          '87.5%': { transform: 'translate(-18px, 18px)' },
          '93.75%': { transform: 'translate(-8px, 12px)' },
        },
        floatRight: {
          '0%, 100%': { transform: 'translate(0px, 0px)' },
          '6.25%': { transform: 'translate(-12px, 15px)' },
          '12.5%': { transform: 'translate(-22px, 25px)' },
          '18.75%': { transform: 'translate(-32px, 32px)' },
          '25%': { transform: 'translate(-40px, 35px)' },
          '31.25%': { transform: 'translate(-48px, 32px)' },
          '37.5%': { transform: 'translate(-54px, 25px)' },
          '43.75%': { transform: 'translate(-58px, 15px)' },
          '50%': { transform: 'translate(-58px, 2px)' },
          '56.25%': { transform: 'translate(-54px, -12px)' },
          '62.5%': { transform: 'translate(-45px, -24px)' },
          '68.75%': { transform: 'translate(-32px, -35px)' },
          '75%': { transform: 'translate(-18px, -42px)' },
          '81.25%': { transform: 'translate(-2px, -45px)' },
          '87.5%': { transform: 'translate(12px, -38px)' },
          '93.75%': { transform: 'translate(8px, -18px)' },
        },
        glow: {
          '0%': { boxShadow: '0 0 20px rgba(99, 102, 241, 0.5)' },
          '100%': { boxShadow: '0 0 40px rgba(99, 102, 241, 0.8)' },
        },
        gradient: {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
      backgroundSize: {
        '300%': '300%',
      },
    },
  },
  plugins: [],
}
